### ISSUE TITLE
Clicksound not working for buttons

### ISSUE THREAD

**Issue by BillyBob360495** [Keksuccino/FancyMenu#981] opened 2024-11-29 17:59 UTC
**Describe the bug**
The clicksound does not work. I have converted the wav files to the correct format as described in the documentation, and disabled all mods I was using. Clicksound still doesn't work, but the hoversound works fine.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a layout to edit
2. Set the clicksound of a button
3. The clicksound does not play, however, other the hoversound plays fine.

**Game Log**
[latest.log](https://github.com/user-attachments/files/17962125/latest.log)

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 3.3.2
 - Forge/Fabric Version 47.3.0
 - Minecraft Version 1.20.1
 - Active Mods: Only mods required for Fancymenu to run.

**Comment by Keksuccino** [comment] 2024-11-29 23:44
Duplicate of #671 and maybe #837

**Closed by Keksuccino** 2024-11-29 23:44 UTC
Labels: bug
