### ISSUE TITLE
OptiFine HD U G5 not compatible [1.12.2]

### ISSUE THREAD

**Issue by PolySaken-I-Am** [Keksuccino/FancyMenu#212] opened 2021-10-30 13:24 UTC
When using OptiFine 1.12.2, panorama backgrounds will not load and instead will be replaced with the tiled dirt background texture. Interestingly the overlay.png texture will still be present overtop.

**To Reproduce**
using forge 1.12.2
1. Install only FM and required mods
2. Install OptiFine
3. Open a layout which uses a panorama background

**Expected behavior**
Panorama background displays normally 

**Basic Informations (please complete the following information):**
 - OS: Ubuntu 21.10
 - FancyMenu 2.3.5
 - Forge  14.23.5.2855
 - Minecraft 1.12.2
 - Active Mods: Optifine, FancyMenu, JustEnoughIDs, konkrete

**Comment by PolySaken-I-Am** [comment] 2021-10-30 13:48
Update: this only happens when fast render is turned on. Probably not a bug, but worth mentioning on the incompatibilities page as other types of panorama work with fast render so it's unexpected.

**Comment by Keksuccino** [comment] 2021-10-30 14:06
Added it to the incompatibility list, thank you! :)

**Comment by PolySaken-I-Am** [comment] 2021-11-04 04:08
Uh might have to reopen this one chief

It would appear the dirt background is some sort of eldritch rotating mask that applies over top of the panorama, but underneath the overlay. I found this out by going into windowed mode, which exposed the sides of the screen to be showing the pano animation:
![Screenshot from 2021-11-04 17-07-27](https://user-images.githubusercontent.com/37032857/140256404-d62231ab-6b8f-457c-bbc3-863b8a0c546c.png)
These slanted areas rotate in and out of view, but the dirt texture stays static.

So I think this actually _is_ a bug.

**Comment by PolySaken-I-Am** [comment] 2021-11-04 04:12
![Screenshot from 2021-11-04 17-11-53](https://user-images.githubusercontent.com/37032857/140256812-a0a84ead-c9f3-4336-b4a7-671f8a7e3ba8.png)
It starts getting weirder the more you squish it, too. These patches rotate in sync but in opposite directions.

**Comment by Keksuccino** [comment] 2021-11-04 04:58
But does it work without OF?

**Comment by PolySaken-I-Am** [comment] 2021-11-05 06:10
Yes, it works perfectly without OF or if fast render is disabled in OF settings.

**Comment by Keksuccino** [comment] 2021-11-05 06:44
Well, but disabling fast rendering fixes it, so it's a compatibility issue with OF, caused by fast rendering :D Disabling is a good workaround. I don't think that I will ever be able to fix this on my end. OF is just weird in too many cases and reverse-engineering the 2000 changes they do to the vanilla code is simply impossible. I'm really sorry, but if it really works without any issues when fast rendering is disabled, then I will close this for now. Thank you very much for the report and and the great info about disabling fast rendering, will help me a lot in the future :)

**Closed by Keksuccino** 2021-11-05 06:44 UTC
Labels: bug

**Comment by PolySaken-I-Am** [comment] 2021-11-05 07:53
Cool, you're welcome :3
