### ISSUE TITLE
NullPointerException in FancyMenu Mod During Server Transfer with Minecraft Snapshot 24w03a

### ISSUE THREAD

**Issue by PublicCode1337** [Keksuccino/FancyMenu#931] opened 2024-08-24 14:05 UTC
**### Description**
When attempting to transfer to another server using the new transfer packet introduced in Minecraft snapshot 24w03a, the FancyMenu mod throws a NullPointerException. This occurs because the mod tries to access a TextWidget (statusTextFancyMenu) that has not been initialized.

**### To Reproduce**

    Connect to a Minecraft server using a version that supports the new transfer packet (from snapshot 24w03a).
    Attempt to transfer to another server using the new transfer functionality.
    Observe the error related to statusTextFancyMenu being null in the game logs.

Expected behavior
The FancyMenu mod should handle the new transfer packet correctly without causing a NullPointerException. The mod should display the appropriate status or update without errors.

Game Log
https://pastebin.com/QcTTPTNn

**Comment by Keksuccino** [comment] 2024-08-25 21:00
This is an exact copy of #929. Why.. ????

**Comment by Keksuccino** [comment] 2024-08-25 21:00
Duplicate of #929

**Closed by Keksuccino** 2024-08-25 21:00 UTC
Labels: bug
