### ISSUE TITLE
Game crashes when setting anchors for each other

### ISSUE THREAD

**Issue by Jerrycyx** [Keksuccino/FancyMenu#892] opened 2024-07-02 12:39 UTC
**Describe the bug**
Game crashes when two elements anchor each other.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create two new elements A and B
2. Set the anchor point of A to B
3. Set the anchor point of B to A
4. Game crashes

**Expected behavior**
Block operation and pop up error message.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version Fabric 0.15.11
 - Minecraft Version 1.20.4

**Comment by Keksuccino** [comment] 2024-07-03 13:48
Duplicate of #872 and #867

**Closed by Keksuccino** 2024-07-03 13:48 UTC
Labels: bug
