### ISSUE TITLE
Add back action in button script

### ISSUE THREAD

**Issue by InTheProcess** [Keksuccino/FancyMenu#879] opened 2024-06-23 23:58 UTC
**Describe your idea**
I have a nested GUI system and I want to be able to add a back button that goes to the previous GUI.  I want this to be dynamic, so whatever the previous GUI is, it will return to it.  This could be done by making a GUI history to effectively implement the back button.

**Comment by Keksuccino** [comment] 2024-06-24 08:02
Duplicate of #511

**Closed by Keksuccino** 2024-06-24 08:02 UTC
Labels: feature request
