### ISSUE TITLE
Add Video Format

### ISSUE THREAD

**Issue by Rockstar-1998** [Keksuccino/FancyMenu#956] opened 2024-10-20 03:24 UTC
The current fancymenu has removed support for video and animation formats, I don't understand why this is, it's a very nice note to be able to display flashy animations on the main MC screen, I'd like to see these features re-added back in a future version if possible, I'd like to have a video as a background on the main screen, that would look cool!

**Comment by Keksuccino** [comment] 2024-10-20 04:06
Because there is no good video library available right now that allows playing videos in Minecraft.
I am waiting for Watermedia to add support for all OSes.

**Comment by Keksuccino** [comment] 2024-10-20 04:07
Duplicate of #685

**Closed by Keksuccino** 2024-10-20 04:06 UTC
Labels: feature request
