### ISSUE TITLE
background bug in language tab

### ISSUE THREAD

**Issue by vitaluska123** [Keksuccino/FancyMenu#901] opened 2024-07-09 17:33 UTC
![image](https://github.com/Keksuccino/FancyMenu/assets/87501597/e1ed5f5d-5e9f-4217-b56f-b51753f8e66e)
background bag (i set header and footer transparrent)

**Basic Informations (please complete the following information):**
OS: Windows 11
fancymenu_fabric_3.2.3_MC_1.20.1
Fabric Version 0.15.11
Minecraft Version 1.20.1

**Comment by vitaluska123** [comment] 2024-07-09 17:35
in shader's page this bug too

**Comment by vitaluska123** [comment] 2024-07-09 17:35
in shader's page this bug too

**Comment by Keksuccino** [comment] 2024-09-24 03:56
Duplicate of #908

**Closed by Keksuccino** 2024-09-24 03:56 UTC
Labels: bug
