### ISSUE TITLE
Unable to open texture pack gui

### ISSUE THREAD

**Issue by MehdiPG** [Keksuccino/FancyMenu#439] opened 2022-11-10 18:37 UTC
**Describe the bug**
When you create a custom button and add the open texture pack selection menu function to it (net.minecraft.client.gui.screens.packs.PackSelectionScreen), it says "unable to open gui"

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to 'Element>new>button'
2. Right Click on the button and select button action
3. Scroll down to 'open gui' and put "net.minecraft.client.gui.screens.packs.PackSelectionScreen"
4. Save and exit layout
5. Click the new button
6. See the error

**Expected behavior**
I expected it to open the texture menu when I click

**Screenshots**
![image](https://user-images.githubusercontent.com/80159231/201178623-2b5ef122-4d30-46ff-bbd6-5832094608d8.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.12.7
 - Forge/Fabric Version Forge 40.1.84
 - Minecraft Version 1.18.2
 - Active Mods TooManyItems

**Comment by Keksuccino** [comment] 2022-11-10 20:01
Duplicate of #429

**Closed by Keksuccino** 2022-11-10 20:01 UTC
Labels: bug
