### ISSUE TITLE
Game crashes when i press the Delete key while editing text content

### ISSUE THREAD

**Issue by Shivter14** [Keksuccino/FancyMenu#613] opened 2023-10-28 18:23 UTC
When i edit text in fancymenu layouts, and press the Delete key to delete the character in front of my cursor, the game crashes.

**To Reproduce**
1. Edit/Create a layout
2. Create a text element body
3. Set text content
4. Press delete key

**Expected behavior**
It should just delete the character after the cursor (like backspace, but it deletes the caracter in front of the cursor)

**Game Log**
https://gist.github.com/Shivter14/bbbe8f6e906743e5900ccf45bb2edc65

**Basic Informations:**
 - OS: Windows 11 Pro Insider Preview Build 23570.ni_prerelease.231013-1312
 - FancyMenu Version 2.14.10-2
 - Fabric Version 2.14.24
 - Minecraft Version 1.20.1
 - Active Mods:
 - ![image](https://github.com/Keksuccino/FancyMenu/assets/98386496/2e57fbf3-3123-462b-bec4-9240285ef4e7)

**Comment by Keksuccino** [comment] 2023-10-28 22:21
Duplicate of #584

**Closed by Keksuccino** 2023-10-28 22:21 UTC
Labels: bug
