### ISSUE TITLE
Render Screen Crash

### ISSUE THREAD

**Issue by Devilswarchild** [Keksuccino/FancyMenu#903] opened 2024-07-15 02:02 UTC
was re-arrangine elements when all of a sudden it crashed.

**Expected behavior**
to not crash when editing layout elements

**Game Log**
[crash log](https://mclo.gs/YSdrNWl)
[latest.log](https://mclo.gs/dc6rEVy)

**Basic Informations (please complete the following information):**
Windows 11 Pro
 - fancymenu_forge_3.2.3_MC_1.20.1.jar
 - Forge 47.3.5
 - Minecraft 1.20.1
 - MineColonies: Dimensional Adventure [modlist](https://github.com/Devilswarchild/MineColonies-Dimensional-Adventure/wiki/2.0.6-Changelog)

**Comment by Keksuccino** [comment] 2024-07-15 17:32
You probably tried to anchor an element to another element, but then tried to anchor the second element to the first one. This is a known bug.

**Comment by Keksuccino** [comment] 2024-07-15 17:32
Duplicate of #867

**Closed by Keksuccino** 2024-07-15 17:32 UTC
Labels: bug
