### ISSUE TITLE
Allow custom slider elements to mimic vanilla slider functionalities such as FOV

### ISSUE THREAD

**Issue by electrified0** [Keksuccino/FancyMenu#561] opened 2023-04-29 18:57 UTC
I'm trying to override the vanilla options menu because it has a button from the Essential Mod that can't be removed by FancyMenu. The custom GUI is finished for the most part, the only problem is that I can't add back the FOV slider.

My suggestion is that you allow users to assign a vanilla action to the slider element. This can be FOV (all I need right now), and possibly volume and chat settings in the future. This feature would be greatly appreciated!

**Comment by Keksuccino** [comment] 2023-04-29 19:50
Duplicate of #463

**Closed by Keksuccino** 2023-04-29 19:50 UTC
Labels: feature request
