### ISSUE TITLE
FancyMenu freezes the game when game intro plays

### ISSUE THREAD

**Issue by eDexiam** [Keksuccino/FancyMenu#121] opened 2021-01-04 00:31 UTC
**Describe the bug**
FancyMenu freezes the game when the game intro starts playing with Optifine installed and the GPU used is of the Intel HD Graphics family

**To Reproduce**
1. Have the latest optifine & fancyMenu installed
2. Start the game making sure you have a game intro animation set up and it's running on an Intel HD Graphics GPU
3. Game freezes at the first few frames of the animation (Do note that sometimes it does not lock up and it's possible to get through it by restarting the game many times)

**Expected behavior**
The game to proceed to the main menu

**Crash Log**
There is no crash or log that would indicate something went wrong when this happens.

**Screenshots**
N/A

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.6.0
 - Forge Version 31.2.8
 - Minecraft Version 1.15.2
 - Active Mods Optifine, FancyMenu, Konkrete

**Comment by Keksuccino** [comment] 2021-01-08 01:35
Hi! Thank you for your report!

Could you please try to update to the newest Forge version for MC 1.15.2? You're using an old (unrecommended) build.

If that doesn't help, could you please send me some more details about your animation?
How much frames at what resolution has the animation? Or is it a GIF animation?
Is the animation playing correctly as background animation of menus?

Thank you very much!

**Comment by lucasboss45** [comment] 2021-01-09 00:17
Hey, the animation is a jpeg sequence of about 1000 frames (30 fps at 1920x1080), forge 31.2.47 had no effect on the issue, the optifine version is HD U G6 Pre5, I am unable to test if it works as a background animation at this time, I will keep informed when I can.

Also I've found a workaround when using the Java version mojang ships with the official launcher (1.8.0_51) the issue is seemingly gone, also when on that version I've noticed that Fancy menu does not catch OpenGL OUT_OF_MEMORY errors when loading them, which also locks up the game as far as I can tell

**Comment by Keksuccino** [comment] 2021-01-09 01:42
There we have the problem. 1000 frames are WAY to much. 1920x1080? This will eat 8GB+ of your RAM without problems. Animations should be as short and small as possible :D 100 frames should be the maximum for your animation resolution.

**Comment by lucasboss45** [comment] 2021-01-09 11:14
Well what's weird about it is that no problems like that occurred on an older version of fancy menu, I can try lowering the resolution and frames.

Also about what I mentioned earlier, is it possible to add a feature where FancyMenu stops loading the animation if an OUT_OF_MEMORY error is generated and replace the animation with a placeholder image?

**Comment by Keksuccino** [comment] 2021-01-10 15:27
Not really :/ At least I didn't found a good way to implement it.
Problem is, when an OutOfMemory is thrown, it's always too late to do much.
Maybe I find a solution for this some day :D

Another question:
You said you're using an Intel processor as GPU (the build-in GPU of the processor) and that would cause these problems. Why are you thinking that? I asked some users with Intel GPUs in my Discord and they all can load game intros without any problems :o

**Comment by lucasboss45** [comment] 2021-01-15 17:21
I've had multiple people have game freezes when using Intel HD Graphics, I can reproduce it on my shitty Intel laptop and get the same result, this doesn't seem to happen on non Intel GPUs though I'm not sure because I'm unable to test that on other iGPUs,  also I can reproduce this issue when running the game on the Java version Mojang ships with the default launcher which Java 1.8.0_51.

**Comment by Keksuccino** [comment] 2021-01-15 22:16
Well, iGPUs aren’t really powerful.. Maybe it’s the GPU itself that causes lags, because it’s too weak for it :/

**Comment by lucasboss45** [comment] 2021-01-19 16:01
Makes sense, there's multiple things involved that are the cause of this so I can imagine that it's difficult to pin point this issue, I've already provided a fix for my users with an older Java revision although I'm not sure if I should keep this open or not as the problem is still there.

**Comment by Keksuccino** [comment] 2021-01-19 17:01
I will keep it open for now and see if I can find something that’s causing it.
If I don’t find anything, I will close it by myself ^^
Thank you very much for reporting this. It’s a very rare/specific issue, but reporting is always the right choice! :)

**Comment by Keksuccino** [comment] 2021-02-03 01:34
Wasn't able to reproduce this :/

**Closed by Keksuccino** 2021-02-03 01:34 UTC
Labels: bug

**Comment by Keksuccino** [comment] 2026-01-21 03:08
Dude this was 2021. If it is happening to you now, it's 100% something else. Please open a new issue with up-to-date information about the problem.
