### ISSUE TITLE
FancyMenu Mod: the background has a slight transparent dirt background

### ISSUE THREAD

**Issue by WunkeyBalls** [Keksuccino/FancyMenu#560] opened 2023-04-29 17:28 UTC
**Describe the bug**
there is a slight transparent dirt background on my animated background, or literally any background options.

**Expected behavior**
whenever you make an animated background, it should be it should be just THAT animation, right? Nope, there is a transparent dirt background converged with the animation.

**Screenshots**
(https://lh3.googleusercontent.com/G34Er73iohYR4ToLj-VN0dEToRXn3lTfO__sAjpiMjrD7LlKIXfA0EFs2UQMZ4cvtSEAw1H5tt1VhOxCwsX52eEUiI7RP6oXHDBuqEk)

**Basic Information:**
 - OS: WIndows
 - FancyMenu Version: 2.14.7 (I think)
 - Forge/Fabric Version: e.g. 43.2.8
 - Minecraft Version: 1.19.2
 - Active Mods : https://github.com/WunkeyBalls/my-mods-for-forge-nothing-useful-here-just-scroll

**Comment by Keksuccino** [comment] 2023-04-29 19:49
Duplicate of #444

**Closed by Keksuccino** 2023-04-29 19:49 UTC
Labels: bug
