### ISSUE TITLE
Incompatibility with Optifine

### ISSUE THREAD

**Issue by AIRLord19** [Keksuccino/FancyMenu#694] opened 2024-02-12 17:10 UTC
Crash

Game Log
[crash-2024-02-12_20.00.23-fml.txt](https://github.com/Keksuccino/FancyMenu/files/14241542/crash-2024-02-12_20.00.23-fml.txt)

 - OS: Windows 11 Pro (23H2)
 - FancyMenu Version 3.0.6
 - Forge Version 47.2.20
 - Minecraft Version 1.20.1
 - Active Mods Optifine

**Comment by mmnvb** [comment] 2024-02-13 07:24
I faced the same issue today. Tried to change the version of fancymenu and it's dependecies. The page on curseforge says that mod requires only konrete to be installed, but game boot claims "melody" mod. Maybe some dependecy links are deprecated?

**Comment by Keksuccino** [comment] 2024-02-14 09:02
@mmnvb This is wrong. All v3 builds on CurseForge have both Konkrete and Melody set as dependency.
<img width="312" alt="Screenshot_1" src="https://github.com/Keksuccino/FancyMenu/assets/35544624/4c2117b2-fa3d-4450-9976-037d6cc0ef0f">

@AIRLord19 Make sure to use latest versions of all mods and Forge and make sure you have both Konkrete and Melody installed. If that doesn't fix the issue please remove OptiFine to see if it's a mod conflict.

**Comment by mmnvb** [comment] 2024-02-14 09:11
Yep, I guess it is a mod conflict for me as well. I would tell you as a find which mod caused it

**Comment by AIRLord19** [comment] 2024-02-14 10:01
> @mmnvbЭто не верно. Для всех сборок v3 на CurseForge в качестве зависимости установлены Konkrete и Melody. <img alt="Скриншот_1" width="312" src="https://private-user-images.githubusercontent.com/35544624/304677535-4c2117b2-fa3d-4450-9976-037d6cc0ef0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDQ5OTcsIm5iZiI6MTcwNzkwNDY5NywicGF0aCI6Ii8zNTU0NDYyNC8zMDQ2Nzc1MzUtNGMyMTE3YjItZmEzZC00NDUwLTk5NzYtMDM3ZDZjYzBlZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA5NTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDRlMzZjZThlNjMxYzQwMjI0ZmM5MDYzMzA3MzJhNWIxZGQxYmI2YTg2NjNjMWEyZTlkMzE5YTJlODkzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tep9WEV2LDGPYgkWVWluxAF2MnInGwt2Fq9ZgvSZzSY">
> 
> @AIRLord19Обязательно используйте последние версии всех модов и Forge и убедитесь, что у вас установлены Konkrete и Melody. Если это не решит проблему, удалите OptiFine, чтобы проверить, не конфликт ли это модов.

Sorry, but everything worked before and I wouldn’t want to play with Optifine (1.18.2) without Optifine, I hope that everything will work in future versions, and I’ll just wait for you.

**Comment by AIRLord19** [comment] 2024-02-14 10:06
> @mmnvbЭто не верно. Для всех сборок v3 на CurseForge в зависимости от установленных Konkrete и Melody. <img alt="Скриншот_1" width="312" src="https://private-user-images.githubusercontent.com/35544624/304677535-4c2117b2-fa3d-4450-9976-037d6cc0ef0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDUzNjEsIm5iZiI6MTcwNzkwNTA2MSwicGF0aCI6Ii8zNTU0NDYyNC8zMDQ2Nzc1MzUtNGMyMTE3YjItZmEzZC00NDUwLTk5NzYtMDM3ZDZjYzBlZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEwMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MjM4Y2VkYzI5MTg2M2FkNGNhNzZjZTg1MDQwZjI4NmI5OTExZDRjNTExZmE2YTgwMzA1YjI0YWY5ZDZmMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2QvTHbFcYGcSTeCFMiBNONYWZV5yUtEG5FUzX_32U8">
> 
> @AIRLord19Обязательно воспользуйтесь последней версией всех модов и Forge и убедитесь, что у вас установлены Konkrete и Melody. Если это не решит проблему, удалите OptiFine, чтобы проверить, нет ли конфликта с этими модами.

And there curseforge is no mod melody
![image](https://github.com/Keksuccino/FancyMenu/assets/159710609/20c0e9ac-dffb-4e7d-956f-b8064eb8441c)

**Comment by Keksuccino** [comment] 2024-02-14 11:07
These are the v2 dependencies.. Look at any v3 build and you will see Melody is correctly set as dependency.

Btw: You shouldn't use Optifine anyways. It is closed-source and breaks lots of mods. Use one of the many [alternatives](http://docs.fancymenu.net/en/optifine-alternatives) instead.

**Comment by Keksuccino** [comment] 2024-02-14 23:42
Please don't close the issue, it isn't solved..

**Comment by AIRLord19** [comment] 2024-02-16 15:51
> Пожалуйста, не закрывайте проблему, она не решена..

okay

**Comment by Keksuccino** [comment] 2024-03-03 06:57
Closed because not reproducible and/or no fix planned.

**Closed by Keksuccino** 2024-03-03 06:57 UTC
Labels: mod conflict
