### ISSUE TITLE
FancyMenu and RRS Not compatible

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Keksuccino/FancyMenu#934] opened 2024-08-30 10:57 UTC
**Describe the issue**
When loading the game with FM & Remove Reloading Screen the game will refuse to load due to an incompatible mod with RRS

Having spoken to the creators of RRS they have confirmed this is an issue with FancyMenu not RRS, is there any chance this can be resolved on 1.20.1? As I see it has been resolved for 1.21 and up.

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] WINDOWS
 - FancyMenu Version v3.2.5
 - Forge Version: 47.3.7
 - Minecraft Version 1.20.1
 - Active Mods FancyMenu & Dependencies + RRS

**Comment by Keksuccino** [comment] 2024-08-31 00:02
Duplicate of #858

**Closed by Keksuccino** 2024-08-31 00:02 UTC
Labels: mod conflict
