### ISSUE TITLE
[help me rhonda] configuration issues

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#12] opened 2020-04-24 03:22 UTC
To start I decided to look at all the packs that depend on your mod and it seems they're all having issues displaying textures as they aren't doing it.

This what I have so far.
![image](https://user-images.githubusercontent.com/3880072/80171488-2c2b6080-85b0-11ea-8762-9643a86c1a2b.png)

my config for what I want to happen
```
customization {
  orientation = bottom-left
  buttonaction = openlink
  x = 1
  width = 106
  action = addbutton
  y = -44
  label = Servers from $2.99
  value = https://bisecthosting.com/kreezxil
  height = 20
}
customization {
	action = addtexture
	path = config/fancymenu/main_bg.png
	orientation = top-left
	x = 1
	y = 1
	width = 1920
	height = 1080
}
customization {
	action = addtexture
	path = config/fancymenu/bisect.png
	orientation = bottom-left
	x = 1
	y = -78
	width = 106
	height = 60
}
```

my folder stucture
![image](https://user-images.githubusercontent.com/3880072/80171615-73195600-85b0-11ea-95a3-f808443abcd2.png)

I want the following image to be the main static non-panoramic image.
![main_bg](https://user-images.githubusercontent.com/3880072/80171664-90e6bb00-85b0-11ea-828b-ddfeeedd95ac.png)

and this image to be above the servers button
![bisect](https://user-images.githubusercontent.com/3880072/80171686-a0fe9a80-85b0-11ea-9dcd-462c4a98c6b3.png)

No matter what I try the full screen and one small texture never render.

![image](https://user-images.githubusercontent.com/3880072/80171785-e4590900-85b0-11ea-9d2a-bb8d93417c8c.png)

**Comment by kreezxil** [comment] 2020-04-24 03:30
if you want to see what i've done so far  you can import this twitch pack. https://drive.google.com/file/d/1dkf847egw1-RzbjyZOQXJlHTDkmVhXNX/view?usp=sharing

**Comment by Keksuccino** [comment] 2020-04-24 03:51
For static backgrounds, use the [texturizebackground](https://github.com/Keksuccino/FancyMenu/wiki/Menu-Customization#texturizebackground) customization action. I will add descriptions for all actions very soon, but for now, I recommend you to use the Layout Creator because everything is very self explaining with it :)

I will look into your texture issue later when I’m back at home. On the first look, everything seems correct, it should render your texture.

**Comment by kreezxil** [comment] 2020-04-24 18:02
The layout creator is bugging on me and it doesn't allow loading of the layout. If open it where a layout was previously designed, the buttons will all be back to default.

I can make a video of that behavior.

**Comment by Keksuccino** [comment] 2020-04-24 18:58
Thats not a bug. The creator only allows to create layouts atm, not editing already existing layouts. Maybe I will add an edit feature in the future. ^^

Have you tried to fix the action with the missing texture? Does it work now or do you still see no images being rendered?

**Comment by kreezxil** [comment] 2020-04-24 19:02
```
customization {
	action = texturizebackground
	path = config/fancymenu/main_bg.png
	orientation = top-left
	x = 1
	y = 1
	width = 1920
	height = 1080
}

customization {
	action = texturizebackground
	path = config/fancymenu/bisect.png
	orientation = bottom-left
	x = 1
	y = -78
	width = 106
	height = 60
}
```
this doesn't work

**Comment by Keksuccino** [comment] 2020-04-24 19:27
You cannot set multiple images as background. You have to set your main_bg.png as background (with "texturizebackground") and your server logo with "addtexture".

P.S.: Variables like orientation, width, height, x and y do not exist for the texturizebackground action.

Try creating a layout with the creator in which you add your main_bg image as background image and your server logo as normal texture. Save it and look into the generated file to see how the actions are looking.

Do you use any other mods to customize or alter the main menu?

**Comment by kreezxil** [comment] 2020-04-24 19:41
i took them out when i decided to try yours

**Comment by kreezxil** [comment] 2020-04-24 19:49
before we go further do you have an example pack or know of a pack that is configured in this way that works that I can look at? if not can you assemble one right quick and you put it on here for examination via the wiki?

**Comment by kreezxil** [comment] 2020-04-24 19:51
and yes, I changed as you suggested
```
customization {
	action = texturizebackground
	path = config/fancymenu/main_bg.png
}

customization {
	action = addtexture
	path = config/fancymenu/bisect.png
	x = 1
	y = -78
	orientation = bottom-left
	width = 108
	height = 60
}
```
There is no background and there is not extra graphic above the button.

**Comment by kreezxil** [comment] 2020-04-24 19:52
I was using packmenu, and like I said it took it because I already knew it was incompatible as I have asked you to make your mod fancymain compatible with it in the past and you basically nixed that Idea, i understand why.

**Comment by kreezxil** [comment] 2020-04-24 20:01
I used the layout construct like you said and it worked but i'm hard pressed to understand how this is different from what I pasted last.

```
customization {
  path = config/fancymenu/main_bg.png
  action = texturizebackground
}

customization {
  path = config/fancymenu/bisect.png
  orientation = top-left
  x = 0
  width = 100
  action = addtexture
  y = 0
  height = 100
}
```
The only difference I see is the order of the elements in the customization block

**Comment by kreezxil** [comment] 2020-04-24 20:16
I'm not sure we should mark this as closed, it's resolved, but there is something going on here that made this more complicated than it should've been.

Since there is a pack download listed in here from my google drive, for someone to experiment with, here is also a config that show all the elements in the right place too.

```
```

**Comment by Keksuccino** [comment] 2020-04-24 20:48
Thank you for telling me about your experience with FancyMenu. I always try to improve it to make it as user-friendly as possible.

The order of variables inside a customization section doesn’t matter, so I don’t think that was the problem here.

I will close it for now but keeping an eye on it and experiment a little bit with similar setups like the one you’ve posted.

**Closed by Keksuccino** 2020-04-24 20:48 UTC
Labels: bug
