### ISSUE TITLE
[1.12.2 | Mod Conflict] Some mixins fail to load

### ISSUE THREAD

**Issue by Jawakun** [Keksuccino/FancyMenu#614] opened 2023-10-30 00:58 UTC
Mixin prepare failed preparing IMixinMainMenuScreen in fancymenu.general.mixin.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'de.keksuccino.fancymenu.mixin.client.IMixinMainMenuScreen' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'de.keksuccino.fancymenu.mixin.client.IMixinMainMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:854) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:713) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) [!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [!mixinbooter-5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:285) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_372]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_372]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at launcher.cOM1.aux(SourceFile:319) [Launcher.jar:?]
	at launcher.cOM1.main(SourceFile:201) [Launcher.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'de.keksuccino.fancymenu.mixin.client.IMixinMainMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1296) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:847) ~[!mixinbooter-5.0.jar:?]
	... 19 more
[02:02:35] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:197) ~[launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_372]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at launcher.cOM1.aux(SourceFile:319) [Launcher.jar:?]
	at launcher.cOM1.main(SourceFile:201) [Launcher.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fancymenu.general.mixin.json:IMixinMainMenuScreen] from phase [DEFAULT] in config [fancymenu.general.mixin.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:590) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:517) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:285) ~[launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12-launcherfixed.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'de.keksuccino.fancymenu.mixin.client.IMixinMainMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:854) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:713) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:285) ~[launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12-launcherfixed.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'de.keksuccino.fancymenu.mixin.client.IMixinMainMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1296) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:847) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:713) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[!mixinbooter-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:285) ~[launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12-launcherfixed.jar:?]
	... 8 more

**Comment by Keksuccino** [comment] 2023-10-30 07:04
That's a mod conflict of some sort. Check your core mods and try to load the game with only FancyMenu + dependencies enabled.

**Comment by Jawakun** [comment] 2023-10-30 19:33
Я вроде всё смотрел, что может конфликтовать?

**Comment by Jawakun** [comment] 2023-10-30 20:05
Or how to enable FancyMenu+ dependencies?

**Comment by Keksuccino** [comment] 2024-01-26 02:57
You remove all mods and only keep FM and its dependencies.
I will close this for now since it's not a bug. If you have more questions, please join the Discord server: #569

**Closed by Keksuccino** 2024-01-26 02:57 UTC
Labels: mod incompatibility
