### ISSUE TITLE
button click sound won't work if the button will open another menu or close menu

### ISSUE THREAD

**Issue by BredyAK** [Keksuccino/FancyMenu#918] opened 2024-08-01 17:42 UTC
**Describe the bug**
button click sound won't work if the button will open another menu or close menu.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. create a button
2. set the button's click sound to anything you want
3. set the button's click action to close the menu or open another menu
4. save the menu
5. open the menu, then click the button you just created, you will find the button's click sound is not played as expected

**Expected behavior**
when clicking a button to open another menu or close the current menu, the button's click sound should play

**Game Log**
the whole action won't generate any log.

**Screenshots**
no need to screen shots.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 3.2.3
 - Forge Version 47.3.0
 - Minecraft Version 1.20.1
 - Active Mods Fancymenu, konkrete_forge_1.8.0_MC_1.20-1.20.1, melody_forge_1.0.3_MC_1.20.1-1.20.4

**Comment by Keksuccino** [comment] 2024-08-02 19:58
Duplicate of #671

**Closed by Keksuccino** 2024-08-02 19:58 UTC
Labels: bug
