### ISSUE TITLE
"Click sound" function doesn't work on a button that opens a world or joins a server

### ISSUE THREAD

**Issue by Legoego19** [Keksuccino/FancyMenu#909] opened 2024-07-19 17:38 UTC
When making a button that opens a world or makes u join a server the click sound effect doesn't play.

1. Make a new "Button" element
2. Change the "Click Sound" Resorce
3. Edit Action Script of the button so it joins and existing world or server
4. There will be no sound and it will just join the world/server

  Expected behavior
When button is pressed it plays a sound and joins the world/server

  Game Log
https://gist.github.com/Legoego19/d6bad9e37b0d65d19ab12675c31f1ca8

 - OS: Windows10
 - FancyMenu_fabric_3.2.5_MC_1.21
 - Fabric Version 0.16.0
 - Minecraft Version 1.20.1
 - Active Mods [Sodium, indium, lithium, Zoomify]

**Comment by Keksuccino** [comment] 2024-07-19 19:09
Duplicate of #671

**Closed by Keksuccino** 2024-07-19 19:09 UTC
Labels: bug
