### ISSUE TITLE
Crash when minimizing and/or switching to a different window

### ISSUE THREAD

**Issue by A0000Xz** [Keksuccino/FancyMenu#721] opened 2024-02-28 07:34 UTC
## Describe the bug

Firstly, after the game starts, the buttons on the fancy menu UI cannot be pressed.
I found that this problem can be solved by simply pressing any previously set button and returning to the title screen.

But if I set a delay effect on the button, it will not appear, which means I can only use the "panoramic view switched by time" that I previously set to refresh the interface by manually switching time before calling out the button.

But the biggest problem is actually that if I try to switch windows, the game will crash, which is more pronounced in the presence of some mods with added mod settings such as "modmenu" or "catalogue". Without these mods, switching windows is a small probability of crashing. (If you can't press the fancy menu button, switching windows seems to be bound to crash)

Interestingly, if you click on another software window to switch to another window, it will not crash, but if you click on the game window to hide it, it will crash.

## To Reproduce

First, start the game and then do nothing, just click on the game icon on the taskbar to hide the window, and then a crash occurs.

## Expected behavior

I am using translation software and it is difficult to convey the meaning of some things accurately,I also noticed that the logs don't seem to reflect many issues, so please take a look at the logs first.

## Game Log

[latest.log](https://github.com/Keksuccino/FancyMenu/files/14430232/latest.log)

## Screenshots

![image](https://github.com/Keksuccino/FancyMenu/assets/122650088/f63bb73f-3c93-4156-8806-82452907ff8a)
![image](https://github.com/Keksuccino/FancyMenu/assets/122650088/74eb3ca4-cf71-48e7-bfb1-286e2f336027)

## Basic Informations (please complete the following information):

 - OS: Windows
 - FancyMenu Version: 3.1.1
 - Forge/Fabric Version: Fabric 0.15.7
 - Minecraft Version: 1.20.1
 - Active Mods: fancymenu_fabric_3.1.1_MC_1.20.1.jar + other mods

**Comment by Keksuccino** [comment] 2024-02-28 07:58
Your latest.log sadly does not seem to have any information about the crash, so please try to reproduce the crash and send me the crash log (not latest.log). Maybe it has some more information. Thank you very much!

**Comment by A0000Xz** [comment] 2024-02-28 14:20
This is also what puzzled me. I have also checked the logs, but did not find any problems, but it did crash, and I found that it no longer has this problem. It's really weird.If it replicates again, I will definitely record a video for you.

**Comment by Keksuccino** [comment] 2024-02-29 09:16
Video would be nice, but the most important part is the crash log.

**Comment by A0000Xz** [comment] 2024-02-29 12:46
https://github.com/Keksuccino/FancyMenu/assets/122650088/63c398a1-ea67-4e21-b245-5879abd04948

I finally reproduced this bug. It's so bizarre because every single crash log has no useful information!
But I've found some traces. I discovered that this bug only appears when I have OBS screen recording software running. Regardless of whether OBS is actively recording, as long as it's open, there's a chance of triggering this crash bug.
Of course, I've started to doubt whether this is actually a bug with the Fancy Menu. However, it does have a specific impact
For example, when this bug occurs, the UI buttons of the Fancy Menu are unresponsive when clicked, and images or buttons with delayed effects do not appear.

**Comment by A0000Xz** [comment] 2024-02-29 12:47
https://github.com/Keksuccino/FancyMenu/assets/122650088/63c398a1-ea67-4e21-b245-5879abd04948

I finally reproduced this bug. It's so bizarre because every single crash log has no useful information!
But I've found some traces. I discovered that this bug only appears when I have OBS screen recording software running. Regardless of whether OBS is actively recording, as long as it's open, there's a chance of triggering this crash bug.
Of course, I've started to doubt whether this is actually a bug with the Fancy Menu. However, it does have a specific impact
For example, when this bug occurs, the UI buttons of the Fancy Menu are unresponsive when clicked, and images or buttons with delayed effects do not appear.

**Comment by Keksuccino** [comment] 2024-03-02 10:56
I am pretty sure this is some graphics driver issue or something. Or it's related to how OBS captures the window. You could try capturing the whole screen instead of just the MC window. But yeah, it's most probably not a bug in FancyMenu, but some other weird stuff going on.

Will close this for now because of it not being a bug, but if you discover new details of how to trigger the bug, etc., feel free to comment here!

Thank you!

**Closed** 2024-03-02 10:57 UTC
Labels: bug
