### ISSUE TITLE
A Modpack Special Version

### ISSUE THREAD

**Issue by BitCyber** [Keksuccino/FancyMenu#774] opened 2024-04-08 13:05 UTC
I would really like it if you could add a different mod for both FancyMenu and DrippyLoadingScreen where the user cannot change the screen whatsoever (unable to use the control + alt + c or whatever it is). This mod then would just require a config file. And would work as a sort of modpack- exclusive version.
My suggestion for uploading it to modrinth is to add it as an additional file.

**Comment by Keksuccino** [comment] 2024-04-08 17:55
There is no point in doing that. The user will always be able go simply edit the config files.

Duplicate of #741

**Comment by Keksuccino** [comment] 2024-04-08 17:55
Duplicate of #741

**Closed by Keksuccino** 2024-04-08 17:55 UTC
Labels: feature request
