### ISSUE TITLE
Client Crash and Playerdata corruption

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Keksuccino/FancyMenu#154] opened 2021-03-21 18:16 UTC
**Describe the bug**
It seems there is a conflict between the mods Fancy Menu and [Create](https://github.com/Creators-of-Create/Create/issues/1286). If I make a schematic using Create, then try to place the Schematic the client crashes whether on a server or singleplayer world. The player data is also corrupted, which has to be cleaned up in NBTExplorer. I originally posted this on the [Create issue tracker](https://github.com/Creators-of-Create/Create/issues/1264#issuecomment-803473906) but was told it was both causing the error.

**To Reproduce**
1. Make a schematic using the Schematic And Quill
2. Write that schematic to an Empty Schematic (item) in a Schematic Table
3. Attempt to place the Schematic in the world or make the Schematic the active item in the hotbar.
2. In singleplayer, the world crashes/client and corrupts the world/player data. On a server is crashes the client and also corrupts the player data, but the world is fine.

**Expected behavior**
Should be able to make and place schematics without crashing or corrupting data.

**Crash Log**
https://pastebin.com/xiY3Lpg5

**Screenshots**
n/a

**Basic Informations (please complete the following information):**
 - OS: Pop OS (based on ubuntu 20.04)
 - FancyMenu Version 2.0.3_MC_1.16.2-1.16.5
 - Forge Version 36.1.0
 - Minecraft Version 1.16.5
 - Active Mods 
   - alexsmobs-1.7.1
   - allomancy-4.2.1
   - angelring-1.16.3-1.3.3
   - Apotheosis-1.16.3-4.4.1
   - AppleSkin-mc1.16.2-forge-1.0.14
   - architectury-1.9.132-forge
   - BiomesOPlenty-1.16.4-13.0.0.431-universal
   - charginggadgets-1.3.0
   - citadel-1.6.2
   - cloth-config-4.11.15-forge
   - comforts-forge-1.16.4-4.0.1.0
   - Controlling-7.0.0.14
   - CookingForBlockheads_1.16.5-9.3.1
   - craftingstation-4.1.1
   - CraftingTweaks_1.16.3-12.2.0
   - create-mc1.16.3_v0.3e
   - createaddition-1.16.4-20210303a
   - Cucumber-1.16.4-4.1.8
   - curios-forge-1.16.5-4.0.5.0
   - CustomStartingGear-1.16.4-2.0.2.1-universal
   - DefaultOptions_1.16.3-12.2.0
   - Disenchanting-forge_1.16.3-1.6.0-alpha
   - fancymenu_2.0.3_MC_1.16.2-1.16.5
   - FarmingForBlockheads_1.16.3-7.3.0
   - FastLeafDecay-v25
   - FastWorkbench-1.16.4-4.5.0
   - forbidden_arcanus-16.2.0-beta-3
   - ftb-backups-2.1.1.6
   - ftb-chunks-1605.2.3-build.71
   - ftb-essentials-1604.1.0.13
   - ftb-gui-library-1605.2.1.41-forge
   - ftb-quests-1605.2.0-build.33-forge
   - ftb-ranks-1604.1.1.11
   - ftb-teams-1604.1.0.16-forge
   - ftb-ultimine-1605.2.0-build.25-forge
   - invtweaks-1.16.4-1.0.1
   - item-filters-1605.2.4-build.30-forge
   - jei-1.16.4-7.6.1.71
   - journeymap-1.16.5-5.7.1
   - konkrete_1.1.5_MC_1.16.2-1.16.5
   - kotlin_libraries-1.0-5
   - kubejs-1605.3.6-build.176-forge
   - kubejs-create-1604.1.0.4
   - metalbarrels-3.3a
   - moreoverlays-1.18.13-mc1.16.5
   - Morpheus-1.16.5-4.2.70
   - MouseTweaks-2.14-mc1.16.2
   - OpenLoader-1.16.5-9.0.3
   - OptiFine_1.16.5_HD_U_G7
   - overloadedarmorbar-5.1.0
   - pamhc2foodcore-1.16.3-1.0.2
   - Patchouli-1.16.4-50
   - PickleTweaks-1.16.4-5.2.1
   - Placebo-1.16.4-4.4.1
   - polymorph-forge-1.16.5-0.24
   - reap-1.16.5-1.0.1
   - ReAuth-1.16-Forge-3.9.3
   - refinedstorage-1.9.12
   - refinedstorageaddons-0.7.2
   - repurposed_structures-1.16.5-2.5.0
   - rhino-1.7.13-build.14
   - rsrequestify-1.16.3-2.0.1
   - shutupexperimentalsettings-1.0.3
   - silent-gear-1.16.3-2.6.9
   - silent-lib-1.16.3-4.9.6
   - SilentGems-1.16.3-3.7.12+115
   - solcarrot-1.16.3-1.9.9
   - StorageDrawers-1.16.3-8.2.2
   - theoneprobe-1.16-3.0.7
   - u_team_core-1.16.5-3.2.0.193
   - useful_backpacks-1.16.5-1.12.0.88
   - valhelsia_core-16.0.6
   - windowlogging-mc1.16.3_v0.0.2

**Comment by Keksuccino** [comment] 2021-03-21 20:25
Seems to be caused by the issue than #155 . This should be fixed in the next update!

**Comment by Keksuccino** [comment] 2021-03-21 22:24
Fixed in FancyMenu v2.0.4! Thank you for your report!

**Closed by Keksuccino** 2021-03-21 22:24 UTC
Labels: bug

**Comment by ClaudiusMinimus** [comment] 2021-03-22 15:20
> Fixed in FancyMenu v2.0.4! Thank you for your report!

This works great! Thank you!
