### ISSUE TITLE
Layouts not loading with custom window title

### ISSUE THREAD

**Issue by KrawuDE** [Keksuccino/FancyMenu#350] opened 2022-07-16 02:58 UTC
**Describe the bug**
Hey Keksuccino, 

I have seen that with the last update you have added a small function that you can change the title in the loading screen.
But there is apparently still a problem.
As soon as I add a name, my own design is not loaded and shows the default theme. But if I remove the name again and restart the game in this regard, my own design is fully loaded.
But i don't know ti's the Same Issue when you load a Costum Title Icon, i haven't this testet yet

**To Reproduce**
1. Change the Name in the config.txt between S:customwindowtitle = 'my modpack name';
2. Load the Game and the Windowtitle is displayed correct
3. Own created Design won't load
4. Close the Game
5. remove the name
6. load the game
7. own created design was correctly loaded

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Crash Log**
no crashes

**Screenshots**
 i think it's not needed

**Basic Informations (please complete the following information):**
 - OS: [Windows]
 - FancyMenu Version [2.11.0]
 - Forge/Fabric Version [Forge - 40.1.54]
 - Minecraft Version [1.18.2]
 - Active Mods [own created Modpack without optifine]

Greetings

**Comment by Keksuccino** [comment] 2022-07-16 17:47
> I have seen that with the last update you have added a small function that you can change the title in the loading screen.

I haven't added any features to change stuff in any loading screen or to change the window title in one of the last updates.
You're probably talking about the feature to edit menu titles? Because that's not the same thing.
Menu titles are the small texts at the top of some menus like the pause menu :)

> Change the Name in the config.txt between S:customwindowtitle = 'my modpack name';

Never manually edit FancyMenu's config if you don't need to. You can edit the config directly in Minecraft.
http://fm.keksuccino.com/en/210x/mod-settings

--------------------

Please try it with only FancyMenu + dependencies installed, to see if it's a compatibility issue. Thank you very much!

**Comment by Keksuccino** [comment] 2022-07-18 22:24
Not reproducible in FancyMenu v2.11.0 Forge 1.18.2.

**Comment by Keksuccino** [comment] 2022-07-19 22:28
Will close this for now because I don't think it's a bug in FM.
Please still try and send all the stuff I was talking about in earlier messages. Will reopen the issue when it's a valid bug.

**Closed by Keksuccino** 2022-07-19 22:28 UTC
Labels: bug, unable to reproduce
