### ISSUE TITLE
Conflict with RRLS4.0.6.1 mod

### ISSUE THREAD

**Issue by McWuKong** [Keksuccino/FancyMenu#897] opened 2024-07-07 19:47 UTC
**Describe the issue**
If using versions 3.1.3 and above,it will conflict with remove reloading screen mod,unable to start game.

**Game Log**
[latest.log](https://github.com/user-attachments/files/16120550/latest.log)

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 3.2.3
 - Fabric Version 0.15.11
 - Minecraft Version 1.20.1
 - 
![1720381448603](https://github.com/Keksuccino/FancyMenu/assets/174964125/49c17a68-f6e8-4a6a-ad7a-d74944a5461e)

**Comment by Keksuccino** [comment] 2024-07-08 14:14
Duplicate of #871

**Closed by Keksuccino** 2024-07-08 14:14 UTC
Labels: mod conflict
