### ISSUE TITLE
[1.18.2] "Randomize Only First Time", doesn't work

### ISSUE THREAD

**Issue by Aarods** [Keksuccino/FancyMenu#727] opened 2024-03-04 19:25 UTC
- Randomize for the first time doesn't work

Steps to reproduce the behavior (e.g.):
1. Go to edit a layout
2. Activate the option of "Randomize for the first"
3. Save and try
4. When you change the slide,  the layout is going to change anyways.

![image](https://github.com/Keksuccino/FancyMenu/assets/110215990/e70acac0-9a1e-492e-bb16-8c53af5e5b46)

 - Windows 11
 - [Forge] v3.1.2 MC 1.18.2
 - Forge 1.18.2 - 40.2.17
 - Minecraft 1.18.2
 - Active Mods: https://gist.github.com/Aarods/f05b374a3672a14ae6c424b4110dd94a

**Comment by Keksuccino** [comment] 2024-03-05 11:34
Some more context would be great but you're most probably trying to randomize universal layouts, which currently doesn't work the way you think. Each screen picks its own random layout, that's why you think it always changes.

This issue is probably a duplicate of #722

**Comment by Keksuccino** [comment] 2024-03-29 07:54
Closed because no answer and not reproducible.

**Closed by Keksuccino** 2024-03-29 07:54 UTC
Labels: bug
