### ISSUE TITLE
crashing from NullPointerException: Registering texture

### ISSUE THREAD

**Issue by IchigoGames** [Keksuccino/FancyMenu#71] opened 2020-07-28 18:32 UTC
**Describe the bug**
[starting singleplayer world crash] this is from a user of my modpack they sent me the crash report and i looked it the only clear thing i saw was ava.lang.NullPointerException: Registering texture and at de.keksuccino.fancymenu.menu.fancy.menuhandler not sure why they are crashing when no one else including my self is having a issue

**To Reproduce**
other then load pack and go into single player not sure.

**Expected behavior**
not crashing

**Crash Log**
https://pastebin.com/Zauij8w0

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version fancymenu_1.4.2_MC_1.15-1.15.2
 - Forge Version 31.2.31
 - Minecraft Version 1.15.2
 - Active Mods the endless frontier 4.4 and 4.5

**Comment by Keksuccino** [comment] 2020-07-29 20:16
I tried to reproduce this error but failed. The error says the menu background texture is empty/never existed. I can't really reproduce this, but the **FULL** log (.minecraft/logs/latest.log) should maybe contain some more errors, happened before the final error that leads to the crash. I could maybe find the origin of this if I had the full log.

**Comment by Keksuccino** [comment] 2020-08-05 20:44
The bug happens in the main menu and not in the singleplayer menu or when loading a world, so I don't think the person which reported this to you really knows when it happened.

Sure, the crash log leads to FancyMenu, but I don't really know if FM was the origin. It happens because MC is struggling to render a non-existent texture (one of FM's textures), but it's not really possible that this texture is unavailable at any point, so I think it was not caused by FM in general. Could be a mod named "Solar Flux" or something that is messing with the texture system and causing issues with FM, but this is just a theory and nothing more. So it could be a possible compatibility issue with "Solar Flux", if there is a mod in your pack with that name.

I'm really sorry but I will close this issue because I cannot reproduce it. Tried everything.
If you have any new informations regarding this, just post it here and I will look at it! :)

**Closed by Keksuccino** 2020-08-05 20:44 UTC
Labels: bug
