### ISSUE TITLE
Crash: Loading 'Improved Backpacks', 'FancyMenu' and New Element: PlayerEntity in Menu.

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#199] opened 2021-09-06 23:16 UTC
**Describe the bug**
If you have a player entity element in your menu and improved backpack installed it will crash the game to desktop, when trying to load the game/menu.

**To Reproduce**
-Create a new Layout with FancyMenu
-Insert "New Element", Player Entity, Playername auto

**Expected behavior**
Load up without crash.

**Crash Log**
https://pastebin.com/9rzmjACV

**Screenshots**
-/-

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: fancymenu_2.2.2-2_MC_1.16.2-1.16.5
 - Forge/Fabric Version: 36.2.4
 - Minecraft Version: 1.16.5
 - Active Mods:
   - fancymenu_2.2.2-2_MC_1.16.2-1.16.5
   - ImprovedBackpacks-1.6.0.0
   - konkrete_1.1.6_MC_1.16.2-1.16.5

**Comment by Keksuccino** [comment] 2021-09-07 00:19
Hi! Haven’t checked it yet, but I think this can be easier fixed from the other mod's side. Would be very nice of you if you could open an issue in the other mod's GitHub too ^^

**Comment by Shorepion** [comment] 2021-09-07 00:29
> Hi! Haven’t checked it yet, but I think this can be easier fixed from the other mod's side. Would be very nice of you if you could open an issue in the other mod's GitHub too ^^

done ✌️

**Comment by socolio** [comment] 2021-09-26 13:55
@Keksuccino this issue is now fixed inside Improved Backpacks. But I should inform you that crash was caused by your side. As far as I know every player entity with NOT remote world should be a child of class "ServerPlayerEntity".

**Closed** 2021-09-26 14:17 UTC
Labels: bug
