### ISSUE TITLE
Fade in buttons

### ISSUE THREAD

**Issue by machinesmith42** [Keksuccino/FancyMenu#144] opened 2021-02-17 02:44 UTC
While buttons can be delayed, the vanilla menu shows them with a fade in animation. Could you add this animation to the game?

**Comment by Keksuccino** [comment] 2021-02-17 05:18
Duplicate of #104.

Yes, it’s already on my list and would be no problem to implement for custom buttons, but it’s a bit trickier for vanilla buttons. That's why I haven’t added it already ^^

**Closed by Keksuccino** 2021-02-17 05:18 UTC
Labels: feature request
