### ISSUE TITLE
Open world to LAN button bug

### ISSUE THREAD

**Issue by Proxwian** [Keksuccino/FancyMenu#841] opened 2024-05-15 15:42 UTC
**Describe the bug**
When I try to add Open to Lan vanilla button and at the same time remove Reports button (which appears after open world to lan button clicked), Open to LAN button also disappears. Also, when I change Report button pos, it doesn't save after I rejoin singleplayer world and clicked Open to LAN again

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Modify in game pause menu
2. Change Open to LAN button position
3. Close editor and click Open to LAN vanilla button
4. Open editor again and remove Reports button
5. Return to main menu
6. Join singleplayer world again
7. There's no Open to LAN vanilla button

**Expected behavior**
1. Open to LAN and Reports buttons works and can be modified independent from each other

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: 3.2.3
 - Forge Version: 47.2.32
 - Minecraft Version: 1.20.1

**Comment by Keksuccino** [comment] 2024-05-16 10:49
Duplicate of #802

**Closed as not planned by Keksuccino** 2024-05-16 10:49 UTC
Labels: bug
