### ISSUE TITLE
Custom texture overlays in scrollable GUIs

### ISSUE THREAD

**Issue by ghost** [Keksuccino/FancyMenu#58] opened 2020-07-13 02:47 UTC
**Describe the bug**
Some gui's dont show the background image as they should

**To Reproduce**
1. Create a layout and set background to a single image
2. look at the 'singleplayer/multiplayer' and 'mods' gui's
3. See error

**Expected behavior**
See the entire background image on the GUI

**Screenshots**
https://imgur.com/a/2GDKPtV

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu 1.4.1_MC_1.15-1.15.2
 - Forge Version 31.2.31
 - Minecraft Version 1.15.2
 - Active Mods No Optifine, many other mods

**Comment by Keksuccino** [comment] 2020-07-13 03:24
That's not a bug, it is supposed to look like this ^^ The overlay on top and bottom of the screen is needed, because MC renders lists very ugly.
They would be visible in the areas which are hidden by these overlays and would glitch through buttons in said areas.

**Comment by MeinKraft** [comment] 2020-07-13 03:26
is there anyway we can add images to hide the areas?  have a top border image, middle image and bottom border image?

layered somehow?

**Comment by Keksuccino** [comment] 2020-07-13 03:39
Nah, that would break the simplicity of the customization system cause it would need me to implement customization actions for specific menus.. I will keep thinking about a way how I could implement this, but I don’t think it can be done in a good way, sorry :/

**Comment by MeinKraft** [comment] 2020-07-13 03:48
could you have an option to change the `textures/gui/options_background.png` image, so at least I can add an image to blend in with the menus/background

similar to this mod  https://www.curseforge.com/minecraft/mc-mods/custom-backgrounds

**Comment by Keksuccino** [comment] 2024-01-26 02:23
Added/Fixed in FancyMenu v3.0.0!

**Closed by Keksuccino** 2024-01-26 02:23 UTC
Labels: feature request, ✅ implemented/fixed in dev
