### ISSUE TITLE
Incompatible with Mod Menu interface

### ISSUE THREAD

**Issue by HistoryOasia-Team** [Keksuccino/FancyMenu#659] opened 2024-01-29 16:24 UTC
**Describe the issue**
Opening mod menu will be very awkward, and the module configuration inside can not be loaded, solved after deleting fancymenu 3.0.2.

**Game Log**
https://mclo.gs/HzxLzT1
Some mod configuration menus crash when opened

**Basic Informations (please complete the following information):**
 - OS: [Windows]
 - FancyMenu Version [3.0.2]
 - Forge/Fabric Version [In crash report]
 - Minecraft Version [1.20.1]
 - Active Mods [In crash report]

**Comment by Keksuccino** [comment] 2024-01-29 16:47
Duplicate of #650

**Closed by Keksuccino** 2024-01-29 16:47 UTC
Labels: mod incompatibility
