### ISSUE TITLE
[1.18] Sound channel doesn't work, volume setting doesnt work

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#299] opened 2022-06-19 14:06 UTC
**Describe the bug**
When I add a new sound element and assign a custom ogg file it plays as expected however when I set the channel to music, the volume controls are still tied to the master volume control. Additionally if I set the volume to 40% in the element it still plays at full volume. This results in a very unpleasant user experience of getting blasted with music until you turn your master volume down. 

**To Reproduce**
1. Add a custom sound element file
2. Set the channel to music
3. Set the volume to 40%
4. volume and channel are ignored

**Expected behavior**
I would expect the sound to play on the correct audio channel and respect volume settings

**Crash Log**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/9200909/174484966-2d02422b-f19b-4a7d-83c1-aab9c3235a38.png)
![image](https://user-images.githubusercontent.com/9200909/174484976-9fc36217-145f-44f1-b38a-ff0d9dab3352.png)

**Basic Informations (please complete the following information):**

 - FancyMenu Version [fancymenu_forge_2.8.0_MC_1.18.2]
 - Forge/Fabric Version [40.0.41]
 - Minecraft Version [e.g. 1.18.2]
 -  auudio_forge_1.0.3_MC_1.18-1.18.2

**Comment by Keksuccino** [comment] 2022-06-19 15:05
- Please try it with only FancyMenu + dependencies installed
- If step 1 doesn't change anything, please send me your `.minecraft/logs/latest.log`

**Comment by Saereth** [comment] 2022-06-19 15:46
Seems the issue with it being on the right audio channel isnt present after I removed/readded the audio file so im not sure what was causing that. The voume setting however still doesn't work.

with only these mods:
![image](https://user-images.githubusercontent.com/9200909/174489219-aacc84c9-206d-4f60-95bb-2350b9717e11.png)

The volume setting is ignored in the audio file settings. here is the latest.log
[latest.log](https://github.com/Keksuccino/FancyMenu/files/8935854/latest.log)

**Comment by Keksuccino** [comment] 2022-06-19 16:36
Can you please send me your setup? You can export your setup via **Setup -> Export** in the customization menu bar.

**Comment by Keksuccino** [comment] 2022-06-23 22:07
> Can you please send me your setup? You can export your setup via Setup -> Export in the customization menu bar.

**Comment by Saereth** [comment] 2022-06-23 22:37
Yes I'll be able to get it to you in about 2 gotta when I get home

**Comment by Saereth** [comment] 2022-06-24 02:55
Here is a curseforge export of the test instance. The main menu volume is currently set to 5% but you'll see...
https://drive.google.com/file/d/1U2CuZNeCvW88gpqiCz8zv-FHv_EM2Ahu/view?usp=sharing
This is the current modlist:
![image](https://user-images.githubusercontent.com/9200909/175452993-a9a3252b-8f96-4ba4-9753-c62fc4e02fcb.png)

MC 1.18.2
forge 40.1.52

**Comment by Keksuccino** [comment] 2022-06-24 17:44
Thank you for sharing your instance!

Soooo.. you've triggered multiple bugs :'D

1. The audio channel didn't work because you had the same audio in a universal layout and your main menu layout, which, for some reason, completely broke that audio, so it kept playing even in menus without customizations enabled and it was locked to the MASTER channel. I removed the audio element from the main menu layout, restarted the instance and now everything works as intended (with only the universal layout audio element).

2. For some reason when going back to the main menu from another menu, the background audio restarts, which shouldn't be the case. This gets fixed when disabling the main menu layout, so something in this layout messes with the audio element. I wasn't able to identify what action/element exactly triggers this, but will keep testing! :)

The background music track is absolutely great btw lmao

**Comment by Saereth** [comment] 2022-06-24 18:00
haha wow thats quite the find, glad it was useful and at least the fix for the volume I can put in immediately so that's great. Thanks a lot!

**Comment by Saereth** [comment] 2022-06-30 13:53
With the latest update most of these issues seem to be resolved by going to a universal layout only for the sound except that when you return to the main menu the sound restarts. You can navigate through any sub menus and it keeps playing as expected but anytime you return to the main menu it starts over. I've double checked there is no audio file on the main menu its all coming from the universal template now.

**Comment by Keksuccino** [comment] 2022-06-30 17:17
They are not resolved, they just happen randomly. I fixed them, the update is just not public yet, because I need to work on it a little more :)

**Comment by Keksuccino** [comment] 2022-06-30 23:07
Both bugs should be fixed in v1.1.1 of the extension (hopefully). Thank you for your report! :)

**Closed by Keksuccino** 2022-06-30 23:07 UTC
Labels: bug
