### ISSUE TITLE
No Chat Reports compat issue

### ISSUE THREAD

**Issue by wExtraBenji** [Keksuccino/FancyMenu#991] opened 2024-12-16 01:15 UTC
**Describe the issue**
The Enable/Disable button for NCR in the multiplayer menu has its' dynamic hover label missing. This only happens when a text element or player entity is added to the multiplayer layout. If the text element is under the popup window, the text from the hover label that is over the text element will show.

**Game Log**
(https://gist.github.com/wExtraBenji/c7a18482e7190e655e378a682637339d)

**Screenshots**
If screenshots would help to explain the issue, please include these.
![NCR1](https://github.com/user-attachments/assets/e64be187-dd50-468b-8e7f-1b87126a03fd)
![NCR2](https://github.com/user-attachments/assets/22753c49-f554-47cf-9d65-2a74bd4bf7a0)
![NCR3](https://github.com/user-attachments/assets/7a4457e7-d615-4210-b20e-dd61a832e6ce)

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - FancyMenu Version 3.3.2_MC_1.20.1
 - Forge Version 47.3.7 + 47.3.11
 - Minecraft Version 1.20.1
 - Active Mods: 
 Fancymenu_forge_3.3.2_MC_1.20.1
 Konkrete_forge_1.8.0_MC_1.20-1.20.1
 Melody_forge_1.0.3_MC_1.20.1-1.20.4
 NoChatReports-FORGE-1.20.1-v2.2.2

**Comment by Keksuccino** [comment] 2024-12-17 23:04
Duplicate of #924

**Closed by Keksuccino** 2024-12-17 23:04 UTC
Labels: mod conflict
