### ISSUE TITLE
Layer stacking with textures?

### ISSUE THREAD

**Issue by JJRicks** [Keksuccino/FancyMenu#9] opened 2020-04-16 05:46 UTC
Hello, thank you so much for making this! A few friends and I have teamed up to make a Hollow Knight resource pack, and so far the menu animation looks fantastic thanks to the mod.
[(short video of what it looks like right now)](https://cdn.discordapp.com/attachments/629451594236297255/700196306945310761/Minecraft__1.15.2_2020-04-15_21-09-01.mp4)

I'd also like to add [this texture](https://cdn.discordapp.com/attachments/629451594236297255/700216327092305920/unknown.png) to make the look more accurate to the game, but as you can see, it goes over top of the splash text. Is there a way layers could be added so it could go underneath the splash? Unfortunately if I put the texture on the animated background, it wouldn't line up anymore if the window size changes.
Thank you so much!

**Comment by JJRicks** [comment] 2020-04-16 06:10
On closer inspection, it looks like the _is_ on top of the texture, but its _drop shadow_ isn't. (How peculiar!) 
[Example](https://cdn.discordapp.com/attachments/696228640945340496/700226254737244171/unknown.png)

**Comment by Keksuccino** [comment] 2020-04-16 11:53
Hi! At first, thank you so much for sharing your main screen! It looks so damn beautiful! :D I love it.

The problem with stacking objects in the render process is, that I can’t really control it. You can imagine the customization process as layer, which is placed over the normal menu. That means, everything you add to a menu (not button modifications, because the buttons are already there) will be rendered over the standard objects.

The only thing I could try to do is, adding a new variable to the type-meta section (in customization files) to define, if all objects of this customization file should be rendered behind everything or above.

**Comment by JJRicks** [comment] 2020-04-16 15:20
Hi, thank you for your reply! I did a bit of testing on my end, and found that `showcustomizationbuttons` seems to change it between the two. (`true` = fully behind, and `false` = just the shadow. Strange indeed!)
![On](https://i.imgur.com/A8anzxw.png)
![Off](https://i.imgur.com/4jej4eG.png)

If putting something fully behind the splash text is impossible at the code level, that's all ok; this mod has gotten me father than I'd ever imagined possible, so thank you for publishing it!

**Comment by Keksuccino** [comment] 2020-04-16 20:32
I tried to reproduce the issue on 1.13.2, but without success :/ Which MC version are you using? Do you have any other mods active?

**Comment by JJRicks** [comment] 2020-04-16 20:33
1.15.2, no other mods at this time 👍

**Comment by Keksuccino** [comment] 2020-04-16 20:40
Okay, I'm so confused :D Everything is working for me in 1.15.2 o.O With and without the customization buttons. Is your MC logo loaded with the customization system or is it the vanilla one with a reource pack?

**Comment by JJRicks** [comment] 2020-04-16 20:40
MC logo is vanilla with a resource pack, but I plan to change it to a texture for higher resolution

**Comment by Keksuccino** [comment] 2020-04-16 20:41
Thats sooo strange. Oh and yes, config, customization files and textures would be great to eventually reproduce the issue ^^

**Comment by JJRicks** [comment] 2020-04-16 20:44
Will try, also uploading now

**Comment by Keksuccino** [comment] 2020-04-16 20:45
Thank you very much!

**Comment by Keksuccino** [comment] 2020-04-16 20:47
> If putting something fully behind the splash text is impossible at the code level, that's all ok; this mod has gotten me father than I'd ever imagined possible, so thank you for publishing it!

That sould be no problem btw. I just want to fix your issue before I start to implement this feature :p

**Comment by JJRicks** [comment] 2020-04-16 20:48
Using fancymenu_0.4.3.1_MC_1.15-1.15.2
Here it is with the resource pack disabled
![Image](https://i.imgur.com/iFpDNWA.jpg)

**Comment by Keksuccino** [comment] 2020-04-16 20:50
Default splash is the important part, I think it could be something with the custom one.

**Comment by Keksuccino** [comment] 2020-04-16 20:51
Ooookay, now I'm out of ideas. I literally don't know why this is even possible :'D

**Comment by JJRicks** [comment] 2020-04-16 20:52
Uploading files, going to remove some of the sounds from the pack so it doesn't take forever haha

**Comment by Keksuccino** [comment] 2020-04-16 20:54
Thanks again, you're a big help. I hope I can reproduce it with your files.. Otherwise, you can just hope that it will fix itself by implementing the new stacking order feature :/

**Comment by JJRicks** [comment] 2020-04-16 20:58
Folder link https://drive.google.com/drive/folders/1clgLbJMnyLK1b9iz5UfawV4B3hBEmK7V?usp=sharing

**Comment by Keksuccino** [comment] 2020-04-16 21:14
Okay, for some reason, it only happens in 1.15, BUT I was able to reproduce it! ^^ Thats good. I'm as confused as before, but now I can try to fix it :'D Thank you for your help!

**Comment by JJRicks** [comment] 2020-04-16 21:14
And thank you so much as well, much appreciated!

**Comment by Keksuccino** [comment] 2020-04-16 22:39
I think, I fixed it! Will be included in the next update!

**Comment by JJRicks** [comment] 2020-04-16 22:59
Awesome! :D (Not to push it, but is moving splash text planned in the future as well?)

**Comment by Keksuccino** [comment] 2020-04-17 00:01
Yes, that will be included in the next update too! :D

Oh, uhm yes, I do ^^ Easiest way to it is via CurseForge, I think I enabled the donation button (PayPal) for FancyMenu, but I'm not 100% sure ^^ I was thinking about a Patreon thing to be included in closed betas or something, but I'm not really sure about it.. So for now, only PayPal, sorry >.<

Little teaser, the rendering order feature is implemented: https://prnt.sc/s0uw1a :D

**Comment by Keksuccino** [comment] 2020-04-21 01:56
FancyMenu v1.0 got released, added the ability to specify the render order and fixed the splash text rendering bug.

**Closed by Keksuccino** 2020-04-21 01:56 UTC
Labels: bug, feature request
