### ISSUE TITLE
Setting 2 elements to be eachothers anchor point will cause a crash

### ISSUE THREAD

**Issue by VoidWarOfficial** [Keksuccino/FancyMenu#867] opened 2024-06-08 01:37 UTC
**Describe the bug**
I set two elements as eachothers anchor points (element A was element B's anchor point, and element B was element A's anchor point)

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Set Element anchor point to another element
2. Set the other elements anchor point to the first one
[latest.log](https://github.com/user-attachments/files/15746066/latest.log)

**Expected behavior**
Expected to be told you cannot set conflicting anchor points

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!

[latest.log](https://github.com/user-attachments/files/15746067/latest.log)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version: Forge 40.2.21
 - Minecraft Version1.18.2

**Comment by KaaayKaay** [comment] 2024-06-16 12:55
Should be **common sense** not to anchor 2 elements to each other anyway.

I did once **lose a lotta progress to this crash** during a session of making the web in minecraft _(basically remaking chromium but just image and text files stored on github servers lmao)_ + a few other less severe times.

**Comment by Keksuccino** [comment] 2024-10-13 03:22
Duplicate of #872

**Closed by Keksuccino** 2024-10-13 03:22 UTC
Labels: bug
