### ISSUE TITLE
Incompatibility with Fastload Reforged

### ISSUE THREAD

**Issue by Proxwian** [Keksuccino/FancyMenu#441] opened 2022-11-13 11:33 UTC
Still have crash even after updating FancyMenu to 2.12.9 and LoadMyResources to 1.0.3

Upd: Client crashes when clicking custom button with action to connect to server

**Comment by Keksuccino** [comment] 2022-11-13 11:36
A log would be good.

**Comment by Proxwian** [comment] 2022-11-13 11:38
On previous version I have this crash report
[crash-2022-11-13_14.04.50-client.txt](https://github.com/Keksuccino/FancyMenu/files/9997076/crash-2022-11-13_14.04.50-client.txt)

After updating to 2.12.9 there is no such file, just client closing itself

**Comment by Keksuccino** [comment] 2022-11-13 11:39
Send me your `logs/latest.log` file after the game closed itself, please.

**Comment by Proxwian** [comment] 2022-11-13 11:46
Upd: Client crashes when clicking custom button with action to connect to server
[latest (1).log](https://github.com/Keksuccino/FancyMenu/files/9997082/latest.1.log)

**Comment by Proxwian** [comment] 2022-11-13 11:49
Also, why do it ever need to be on a server side? xD
Or, you mean, local server on single player world?

**Comment by Keksuccino** [comment] 2022-11-13 11:55
> Also, why do it ever need to be on a server side? xD
> Or, you mean, local server on single player world?

To let mods like FTB Quests run FancyMenu commands for users.

**Comment by Keksuccino** [comment] 2022-11-13 21:38
> Upd: Client crashes when clicking custom button with action to connect to server [latest (1).log](https://github.com/Keksuccino/FancyMenu/files/9997082/latest.1.log)

Joining servers via custom button works fine for me. Could be a mod confict or something other, because your log looks really strange.

Is this also happening when using FancyMenu v2.12.6? Can you please try it with this version?

**Comment by benderjm** [comment] 2022-11-13 21:54
I was just having this issue too, and it turns out the crash was being caused by Fastload Reforged version 1.3.3, and downgrading that back to 1.2.1 fixed the crash

**Comment by Keksuccino** [comment] 2022-11-17 00:11
Closed because not reproducible and no response.

**Comment by Proxwian** [comment] 2022-12-24 17:26
Still applicable with latest Fastload, please reopen

**Comment by Proxwian** [comment] 2022-12-24 17:27
[crash-2022-12-25_00.21.23-client.txt](https://github.com/Keksuccino/FancyMenu/files/10298961/crash-2022-12-25_00.21.23-client.txt)

As [benderjm](https://github.com/benderjm) said, the only way to fix this is downgrade fastload reforged to 1.2.1

**Comment by Keksuccino** [comment] 2023-01-04 03:58
> [crash-2022-12-25_00.21.23-client.txt](https://github.com/Keksuccino/FancyMenu/files/10298961/crash-2022-12-25_00.21.23-client.txt)
> 
> As [benderjm](https://github.com/benderjm) said, the only way to fix this is downgrade fastload reforged to 1.2.1

Please send me the full log, I can't do anything with a crash log that tells me nothing.

**Comment by Proxwian** [comment] 2023-01-04 10:25
Looks like was fixed in latest fancymenu, can't reproduce anymore

**Closed** 2023-01-04 14:58 UTC
Labels: mod incompatibility
